# Generated by Django 2.0.1 on 2018-02-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_postad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postad',
            name='category',
        ),
        migrations.AlterField(
            model_name='postad',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
