# Generated by Django 2.0.1 on 2018-02-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_movies_cinema_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinema',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ('movie_name',)},
        ),
        migrations.RemoveField(
            model_name='movies',
            name='cinema_name',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='name',
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cinema.Cinema'),
        ),
    ]
