# Generated by Django 2.0.1 on 2018-02-08 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_auto_20180208_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='movies',
            name='movie_name',
        ),
        migrations.AddField(
            model_name='movies',
            name='name',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AddField(
            model_name='movies',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
