# Generated by Django 2.0.1 on 2018-02-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_auto_20180208_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='cinema_name',
            field=models.ManyToManyField(to='cinema.Cinema'),
        ),
    ]
