# Generated by Django 2.0.1 on 2018-02-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_movies_cinema_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
