# Generated by Django 2.0.1 on 2018-02-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_auto_20180208_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='cinema_name',
        ),
    ]
