# Generated by Django 2.0.1 on 2018-02-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_remove_movies_cinema_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_name_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cinema.Cinema'),
        ),
    ]
